/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nrangasa' at '1/20/19 3:55 PM' with Gradle 2.14.1
 *
 * @author nrangasa, @date 1/20/19 3:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
